query {
    getPatientById(id: "5f18a20e06d9390860eac4d0") {
        success
        message
        patient {
            id
            userName
            firstName
            middleName
            lastName
            gender
            email
            phone
            addressLine1
            addressLine2
            city
            state
            county
            zipCode
            isSmoker
            birthday
        }
    }
}
