mutation updateProvider {
    updateProvider(
        id: "5f167a6750b07e0593982281"
        input: { firstName: "Andrew", lastName: "Voila", email: "doctor@yopmail.com", phone: "512-112-2222" }
    ) {
        success
        message
        provider {
            id
            userName
            firstName
            lastName
            email
            phone
        }
    }
}
