query {
    getPatients {
        id
        userName
        firstName
        middleName
        lastName
        gender
        email
        phone
        addressLine1
        addressLine2
        city
        state
        county
        zipCode
        isSmoker
        birthday
    }
}
