mutation updatePatient {
    updatePatient(
        id: "5f167a4850b07e0593982280"
        input: { firstName: "StanDaughter", lastName: "Lee", email: "LLL2OOO@yopmail.com", phone: "512-112-2222" }
    ) {
        success
        message
        patient {
            id
            userName
            firstName
            lastName
            email
            phone
        }
    }
}
